
name: "Benchmark Go Client"
on: ["push", "pull_request"]
jobs:
  benchmark:
    runs-on: "ubuntu-latest"
    env:
      GOPATH: "${{ github.workspace }}/go"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go_version: [ "1.20" ]
        member_count: [ 1, 3 ]
      fail-fast: false
    defaults:
      run:
        shell: "bash"
        working-directory: "${{ github.workspace }}/hazelcast-go-client"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v4"
        with:
          path: "${{ github.workspace }}/hazelcast-go-client"

      - uses: ./.github/actions/build
        with:
          GO_VERSION: ${{ matrix.go_version }}
          OS: ${{ matrix.os }}
          REPO_PATH: "${{ github.workspace }}/hazelcast-go-client"

      - name: "Run Benchmarks, ${{ matrix.member_count }} Member(s)"
        run: |
          MEMBER_COUNT=3 WARMUPS=3 make benchmark
        env:
          MEMBER_COUNT: ${{ matrix.member_count }}
          WARMUPS: 3
