name: Go nightly build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  test_client:
    runs-on: ${{ matrix.os }}
    name: Run tests of master on ${{ matrix.os }} with Go ${{ matrix.go_version }}
    if: github.repository == 'hazelcast/hazelcast-go-client'
    strategy:
        matrix:
            os: [ ubuntu-latest ]
            go_version: [ "1.20", "1.21" ]
        fail-fast: false
    defaults:
      run:
        shell: "bash"
        working-directory: "${{ github.workspace }}/hazelcast-go-client"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v4"
        with:
          path: "${{ github.workspace }}/hazelcast-go-client"

      - uses: ./hazelcast-go-client/.github/actions/build
        with:
          GO_VERSION: ${{ matrix.go_version }}
          OS: ${{ matrix.os }}
          REPO_PATH: "${{ github.workspace }}/hazelcast-go-client"

      - name: Test
        env:
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
          ENABLE_SSL: 1
          MEMBER_COUNT: 3
        run: |
          make test-cover
