name: "Test Go Client with Race Detector Enabled"
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      GOPATH: "${{ github.workspace }}"
      HZ_VERSION: "5.1.2"
    defaults:
      run:
        shell: "bash"
        working-directory: "$HOME/hazelcast-go-client"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
        with:
          path: "$HOME/hazelcast-go-client"

      - name: "Install Dependencies"
        run: |
          sudo apt-get update

          java --version
          type -a java

          sudo apt-get install -y openjdk-17-jdk-headless

          java --version
          type -a java