
name: "Test Go Client"

on: ["push", "pull_request"]
jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go_version: [ "1.20" ]
        arch: [ "amd64", "386" ]
      fail-fast: false
    defaults:
      run:
        shell: "bash"
        working-directory: "${{ github.workspace }}/hazelcast-go-client"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v4"
        with:
          path: "${{ github.workspace }}/hazelcast-go-client"

      - name: "Run Checkers"
        run: |
          ls .

      - name: "Run Checkers"
        run: |
          ls ./hazelcast-go-client

      - uses: ./hazelcast-go-client/.github/actions/build
        with:
          GO_VERSION: ${{ matrix.go_version }}
          OS: ${{ matrix.os }}
          REPO_PATH: "${{ github.workspace }}/hazelcast-go-client"

      - name: "Run Checkers"
        run: |
          make check

      - name: "Run All Tests"
        run: |
          make test-all
        env:
          GOARCH: ${{ matrix.arch }}
