
name: "Test Windows"
on: ["push", "pull_request"]
jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: "bash"
    steps:
      - shell: bash
        run: |
          echo "GITHUB_REPOSITORY is ${GITHUB_REPOSITORY}"
