name: "Test Go Client with Race Detector Enabled"

on: ["push", "pull_request"]
jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go_version: [ "1.20" ]
      fail-fast: false
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v4"

      - uses: ./.github/actions/build
        with:
          GO_VERSION: ${{ matrix.go_version }}
          OS: ${{ matrix.os }}

      - name: "Run Tests with Race Detection"
        run: |
          make test-race
